version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    volumes:
      - ./:/var/www/laravel-docker
    ports:
      - '8098:80'
    links:
      - fpm
    networks:
      - app-network
  mysql:
    image: mysql:5.7
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=poligon
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    volumes:
      - ./:/var/www/laravel-docker
    links:
      - mysql
    networks:
      - app-network
volumes:
  db:
networks:
  app-network:
    driver: bridge
